type Mutation {

    addVote(character: ID!): ResultOperation!
    updateVote(character: ID!, idVote: ID!): ResultOperation!
    # para cambiar el voto a otro actor

    deleteVote(id: ID!): ResultOperation!


}